COMPILE_FLAGS = $(INCLUDE_DIRS) \
				$(POSTGRES_CPPFLAGS) \
				$(WEBTOOLKIT_CPPFLAGS) \
				$(BOOST_CPPFLAGS) \
				$(OPENSSL_INCLUDES) \
				$(PTHREAD_CFLAGS) \
				$(COVERAGE_CFLAGS) \
				$(SOURCE_DEFINES)  \
				$(WARNING_FLAGS) $(TEST_DEFINES)
